In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("SS_meridian.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  691 non-null    int64
 1   Survived     691 non-null    int64
 2   Pclass       691 non-null    int64
 3   Name         691 non-null    object
 4   Sex          691 non-null    object
 5   Age          634 non-null    float64
 6   SibSp        691 non-null    int64
 7   Parch        691 non-null    int64
 8   Ticket       691 non-null    object
 9   Fare         691 non-null    float64
 10  Cabin        149 non-null    object
 11  Embarked     691 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 64.9+ KB

In [4]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,691.000000,691.000000,691.000000,634.000000,691.000000,691.000000,691.000000
mean,346.000000,0.573082,2.108538,31.534385,0.751085,0.560058,35.100593
std,199.618803,0.494988,0.850285,14.198957,0.995051,0.802404,40.895254
min,1.000000,0.000000,1.000000,0.500000,0.000000,0.000000,3.500000
25%,173.500000,0.000000,1.000000,21.225000,0.000000,0.000000,7.440000
50%,346.000000,1.000000,2.000000,31.600000,0.000000,0.000000,15.070000
75%,518.500000,1.000000,3.000000,40.775000,1.000000,1.000000,54.585000
max,691.000000,1.000000,3.000000,74.000000,4.000000,3.000000,203.150000

In [11]:
df.describe(include="object")

                    Name   Sex   Ticket Cabin Embarked
count                691   691      691   149      691
unique               637     2      688   131        3
top     Green, Mr. Edwin  male  SM28837   C16        L
freq                   3   414        2     3      279

In [13]:
df.shape

(691, 12)

In [14]:
df.Ticket.value_counts()

Ticket
SM28837    2
SM61505    2
SM86556    2
SM70415    1
SM49405    1
          ..
SM51999    1
SM27423    1
SM45187    1
SM50906    1
SM30204    1
Name: count, Length: 688, dtype: int64

In [16]:
df.describe(include=["object","int","float"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,691.000000,691.000000,691.000000,691,691,634.000000,691.000000,691.000000,691,691.000000,149,691
unique,NaN,NaN,NaN,637,2,NaN,NaN,NaN,688,NaN,131,3
top,NaN,NaN,NaN,"Green, Mr. Edwin",male,NaN,NaN,NaN,SM28837,NaN,C16,L
freq,NaN,NaN,NaN,3,414,NaN,NaN,NaN,2,NaN,3,279
mean,346.000000,0.573082,2.108538,NaN,NaN,31.534385,0.751085,0.560058,NaN,35.100593,NaN,NaN
std,199.618803,0.494988,0.850285,NaN,NaN,14.198957,0.995051,0.802404,NaN,40.895254,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.500000,0.000000,0.000000,NaN,3.500000,NaN,NaN
25%,173.500000,0.000000,1.000000,NaN,NaN,21.225000,0.000000,0.000000,NaN,7.440000,NaN,NaN
50%,346.000000,1.000000,2.000000,NaN,NaN,31.600000,0.000000,0.000000,NaN,15.070000,NaN,NaN
75%,518.500000,1.000000,3.000000,NaN,NaN,40.775000,1.000000,1.000000,NaN,54.585000,NaN,NaN
max,691.000000,1.000000,3.000000,NaN,NaN,74.000000,4.000000,3.000000,NaN,203.150000,NaN,NaN

In [18]:
result=df.describe(include="all")

In [19]:
result.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,691.0,691.000000,691.000000,691,691,634.000000,691.000000,691.000000,691,691.000000,149,691
unique,NaN,NaN,NaN,637,2,NaN,NaN,NaN,688,NaN,131,3
top,NaN,NaN,NaN,"Green, Mr. Edwin",male,NaN,NaN,NaN,SM28837,NaN,C16,L
freq,NaN,NaN,NaN,3,414,NaN,NaN,NaN,2,NaN,3,279
mean,346.0,0.573082,2.108538,NaN,NaN,31.534385,0.751085,0.560058,NaN,35.100593,NaN,NaN

In [20]:
result.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
min,1.0,0.0,1.0,NaN,NaN,0.500,0.0,0.0,NaN,3.500,NaN,NaN
25%,173.5,0.0,1.0,NaN,NaN,21.225,0.0,0.0,NaN,7.440,NaN,NaN
50%,346.0,1.0,2.0,NaN,NaN,31.600,0.0,0.0,NaN,15.070,NaN,NaN
75%,518.5,1.0,3.0,NaN,NaN,40.775,1.0,1.0,NaN,54.585,NaN,NaN
max,691.0,1.0,3.0,NaN,NaN,74.000,4.0,3.0,NaN,203.150,NaN,NaN

In [21]:
result["Age"]

count     634.000000
unique           NaN
top              NaN
freq             NaN
mean       31.534385
std        14.198957
min         0.500000
25%        21.225000
50%        31.600000
75%        40.775000
max        74.000000
Name: Age, dtype: float64

In [22]:
result[["Age","Sex"]]

               Age   Sex
count   634.000000   691
unique         NaN     2
top            NaN  male
freq           NaN   414
mean     31.534385   NaN
std      14.198957   NaN
min       0.500000   NaN
25%      21.225000   NaN
50%      31.600000   NaN
75%      40.775000   NaN
max      74.000000   NaN

In [23]:
result

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,691.000000,691.000000,691.000000,691,691,634.000000,691.000000,691.000000,691,691.000000,149,691
unique,NaN,NaN,NaN,637,2,NaN,NaN,NaN,688,NaN,131,3
top,NaN,NaN,NaN,"Green, Mr. Edwin",male,NaN,NaN,NaN,SM28837,NaN,C16,L
freq,NaN,NaN,NaN,3,414,NaN,NaN,NaN,2,NaN,3,279
mean,346.000000,0.573082,2.108538,NaN,NaN,31.534385,0.751085,0.560058,NaN,35.100593,NaN,NaN
std,199.618803,0.494988,0.850285,NaN,NaN,14.198957,0.995051,0.802404,NaN,40.895254,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.500000,0.000000,0.000000,NaN,3.500000,NaN,NaN
25%,173.500000,0.000000,1.000000,NaN,NaN,21.225000,0.000000,0.000000,NaN,7.440000,NaN,NaN
50%,346.000000,1.000000,2.000000,NaN,NaN,31.600000,0.000000,0.000000,NaN,15.070000,NaN,NaN
75%,518.500000,1.000000,3.000000,NaN,NaN,40.775000,1.000000,1.000000,NaN,54.585000,NaN,NaN
max,691.000000,1.000000,3.000000,NaN,NaN,74.000000,4.000000,3.000000,NaN,203.150000,NaN,NaN

In [25]:
result.iloc[1]

PassengerId    NaN
Survived       NaN
Pclass         NaN
Name           637
Sex              2
Age            NaN
SibSp          NaN
Parch          NaN
Ticket         688
Fare           NaN
Cabin          131
Embarked         3
Name: unique, dtype: object

In [27]:
result.loc["unique"]

PassengerId    NaN
Survived       NaN
Pclass         NaN
Name           637
Sex              2
Age            NaN
SibSp          NaN
Parch          NaN
Ticket         688
Fare           NaN
Cabin          131
Embarked         3
Name: unique, dtype: object

In [29]:
df.Embarked.unique()

array(['M', 'L', 'C'], dtype=object)

In [30]:
df.Sex.unique()

array(['female', 'male'], dtype=object)

In [31]:
df.Cabin.unique()

array([nan, 'A43', 'A66', 'B59', 'A86', 'E46', 'B25', 'A93', 'D88', 'A41',
       'C99', 'B70', 'B62', 'D80', 'D82', 'C48', 'C60', 'A49', 'A21',
       'C59', 'B60', 'A83', 'D94', 'B32', 'C16', 'A82', 'C77', 'D89',
       'A20', 'D62', 'B79', 'F28', 'B83', 'E35', 'A39', 'C88', 'D54',
       'B51', 'F40', 'C81', 'E23', 'C62', 'D52', 'A50', 'C68', 'C22',
       'C21', 'A11', 'B85', 'D45', 'A77', 'A60', 'A19', 'B65', 'E38',
       'C87', 'D97', 'E55', 'A63', 'C67', 'B91', 'D78', 'C18', 'C75',
       'D81', 'D20', 'E62', 'A40', 'D24', 'A26', 'F32', 'F50', 'B46',
       'B56', 'D53', 'D58', 'A35', 'B41', 'F29', 'A53', 'A65', 'A36',
       'F65', 'E33', 'D44', 'B15', 'C32', 'A16', 'B93', 'A18', 'C37',
       'B94', 'C14', 'C52', 'B27', 'D69', 'F70', 'F75', 'D14', 'B68',
       'B54', 'E28', 'F27', 'D47', 'D51', 'B67', 'B82', 'B69', 'B99',
       'B24', 'B20', 'B17', 'C38', 'B38', 'C27', 'D91', 'F45', 'A61',
       'E77', 'F41', 'A67', 'B19', 'D86', 'C85', 'E32', 'E42', 'C53',
       'A90', 'E66', 'F21', 'A59', 'B72'], dtype=object)

## finding Missing values

In [32]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,True,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
686,False,False,False,False,False,False,False,False,False,False,False,False
687,False,False,False,False,False,False,False,False,False,False,True,False
688,False,False,False,False,False,False,False,False,False,False,True,False
689,False,False,False,False,False,False,False,False,False,False,False,False
690,False,False,False,False,False,False,False,False,False,False,True,False

In [33]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             57
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          542
Embarked         0
dtype: int64

In [35]:
df.Age.isna()

0      False
1      False
2       True
3      False
4      False
       ...
686    False
687    False
688    False
689    False
690    False
Name: Age, Length: 691, dtype: bool

In [36]:
df[df.Age.isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
17,18,1,3,"Adams, Mr. William",male,NaN,3,0,SM99505,3.56,NaN,M
43,44,0,2,"Mitchell, Mr. Clarence",male,NaN,0,1,SM55603,9.12,NaN,L
46,47,1,1,"Garcia, Countess Harriet",female,NaN,0,2,SM95426,50.94,A41,L
47,48,0,3,"Miller, Miss Anna",female,NaN,0,0,SM88134,4.87,NaN,M
55,56,1,1,"Evans, Miss Alice",female,NaN,2,0,SM29848,119.46,B62,C
67,68,0,3,"Green, Mr. Thomas",male,NaN,1,1,SM93681,7.62,NaN,L
73,74,1,2,"Thompson, Mr. Arthur",male,NaN,0,1,SM77411,6.06,NaN,L
77,78,1,1,"Martinez, Countess Elsie",female,NaN,0,1,SM23425,79.71,C48,L
87,88,0,2,"Walker, Mr. James",male,NaN,0,0,SM99573,25.08,NaN,M
88,89,1,2,"Anderson, Mr. Harry",male,NaN,1,0,SM25509,22.93,NaN,L
111,112,1,2,"Mitchell, Mr. Stanley",male,NaN,0,0,SM63143,23.18,NaN,C
115,116,0,3,"Adams, Mr. Herbert",male,NaN,3,1,SM87894,5.72,NaN,M
122,123,0,3,"Green, Mr. Walter",male,NaN,0,1,SM90149,6.88,NaN,M
126,127,1,1,"Phillips, Miss Alice",female,NaN,0,0,SM69770,72.06,D94,C
127,128,0,2,"Hall, Mr. Michael",male,NaN,0,1,SM89194,11.73,NaN,C
135,136,0,3,"Phillips, Mr. Thomas",male,NaN,2,2,SM33474,7.07,NaN,L
143,144,1,1,"Garcia, Countess Winifred",female,NaN,1,1,SM81496,155.52,A20,L
148,149,0,2,"Roberts, Mr. Thomas",male,NaN,0,0,SM54663,9.07,NaN,M
154,155,1,2,"Green, Mr. Edwin",male,NaN,0,0,SM37102,15.82,NaN,M
164,165,0,2,"Taylor, Miss Agnes",female,NaN,1,0,SM21247,10.55,E35,M
184,185,0,3,"Lee, Mr. John",male,NaN,1,1,SM22560,6.91,NaN,C
235,236,1,2,"Adams, Mrs. Gladys",female,NaN,0,1,SM50906,22.43,NaN,L
265,266,0,1,"Rogers, Dr. Henry",male,NaN,1,0,SM35415,92.33,NaN,L
276,277,1,1,"Lopez, Lady Violet",female,NaN,1,0,SM16428,164.96,NaN,C
299,300,0,3,"Thomas, Mr. John",male,NaN,0,0,SM89073,13.15,NaN,L
300,301,1,3,"Jones, Miss Rose",female,NaN,1,0,SM30582,10.62,NaN,M
302,303,1,3,"Williams, Miss Edith",female,NaN,0,3,SM60579,6.15,NaN,L
335,336,0,3,"Turner, Mr. Alfred",male,NaN,3,0,SM88494,7.49,NaN,C
340,341,0,3,"Jones, Mr. George",male,NaN,0,0,SM92090,14.05,NaN,M
378,379,0,3,"Campbell, Mrs. Grace",female,NaN,3,0,SM59827,3.50,NaN,M
388,389,0,3,"Parker, Miss Lillian",female,NaN,0,3,SM40464,3.50,NaN,C
395,396,1,1,"Evans, Countess Alice",female,NaN,1,0,SM22656,121.06,NaN,L
396,397,0,3,"Turner, Mr. James",male,NaN,1,0,SM10753,9.09,NaN,C
403,404,1,2,"King, Miss Mabel",female,NaN,0,0,SM49562,24.29,E33,M
413,414,1,3,"Young, Miss Martha",female,NaN,0,0,SM75726,3.50,NaN,C
420,421,0,2,"Sanchez, Miss Martha",female,NaN,2,0,SM45268,9.73,NaN,C
432,433,0,1,"Phillips, Capt. Michael",male,NaN,2,0,SM66072,3.50,B93,L
434,435,0,3,"Morris, Miss Cecelia",female,NaN,0,0,SM32843,11.82,NaN,L
456,457,0,3,"Adams, Mr. Michael",male,NaN,2,1,SM47560,8.67,NaN,L
463,464,0,3,"Allen, Mr. Edward",male,NaN,0,0,SM50907,3.50,NaN,C
465,466,0,3,"Baker, Mr. Frederick",male,NaN,2,1,SM49405,3.59,NaN,L
480,481,1,2,"Morris, Mrs. Cecelia",female,NaN,1,1,SM40497,21.07,NaN,C
488,489,1,2,"King, Mrs. Winifred",female,NaN,0,1,SM42859,15.99,NaN,C
509,510,0,3,"Green, Mr. Clarence",male,NaN,3,0,SM63347,7.57,NaN,M
510,511,0,2,"Johnson, Mr. George",male,NaN,2,1,SM38091,12.27,NaN,C
511,512,0,2,"Martinez, Mr. Leonard",male,NaN,1,2,SM27133,21.58,NaN,L
536,537,0,3,"Young, Mr. Alfred",male,NaN,0,0,SM30325,8.98,NaN,M
571,572,1,3,"Sanchez, Mrs. Elsie",female,NaN,1,0,SM61733,16.70,NaN,C
579,580,1,1,"Parker, Col. Harold",male,NaN,0,1,SM33777,117.77,NaN,C
582,583,1,1,"Hernandez, Miss Clara",female,NaN,0,0,SM19545,68.70,B99,L
584,585,1,3,"Smith, Mr. David",male,NaN,0,1,SM28664,12.46,NaN,L
618,619,1,1,"Hernandez, Mrs. Violet",female,NaN,0,0,SM23238,110.54,D91,M
628,629,1,2,"Scott, Miss Gladys",female,NaN,0,0,SM40305,24.63,NaN,C
644,645,0,1,"Miller, Rev. George",male,NaN,0,1,SM59192,20.15,B19,C
666,667,1,1,"Lee, Mrs. Clara",female,NaN,0,1,SM75513,66.31,A90,C
675,676,1,1,"Evans, Dr. Alfred",male,NaN,0,0,SM37925,104.12,NaN,L

In [37]:
df[df.Age.isna()].shape

(57, 12)

## More on filtering and data selection

In [41]:
df[["Sex","PassengerId"]]

        Sex  PassengerId
0    female            1
1    female            2
2    female            3
3    female            4
4    female            5
..      ...          ...
686  female          687
687    male          688
688  female          689
689  female          690
690  female          691

[691 rows x 2 columns]

In [42]:
df.loc[0]

PassengerId                    1
Survived                       0
Pclass                         3
Name           Clark, Miss Mabel
Sex                       female
Age                         22.9
SibSp                          2
Parch                          1
Ticket                   SM70415
Fare                         3.5
Cabin                        NaN
Embarked                       M
Name: 0, dtype: object

In [43]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [44]:
df.loc[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L

In [45]:
df.iloc[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C

In [46]:
df.loc[0:3,0:3]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [47]:
df.iloc[0:3,0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       3
2            3         1       2

In [49]:
df.loc[0:2,"PassengerId":"Pclass"]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       3
2            3         1       2

In [53]:
df.loc[:2,:"Pclass"]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       3
2            3         1       2

In [54]:
df.Sex=="female"

0       True
1       True
2       True
3       True
4       True
       ...
686     True
687    False
688     True
689     True
690     True
Name: Sex, Length: 691, dtype: bool

In [55]:
df[df.Sex=="female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
685,686,1,1,"Lee, Mrs. Violet",female,38.0,3,0,SM39824,143.13,NaN,C
686,687,1,1,"Jackson, Lady Florence",female,34.6,0,0,SM85340,100.78,B72,C
688,689,1,1,"Jackson, Lady Violet",female,45.7,0,0,SM87624,48.47,NaN,L
689,690,1,1,"Harris, Mrs. Gladys",female,43.2,0,0,SM59207,42.19,D20,M
690,691,0,3,"Green, Mrs. Clara",female,33.1,0,0,SM30204,5.21,NaN,M

In [56]:
df.Age>23

0      False
1       True
2      False
3       True
4       True
       ...
686     True
687     True
688     True
689     True
690     True
Name: Age, Length: 691, dtype: bool

In [58]:
df[df.Age>23].sort_values("Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
155,156,0,3,"Campbell, Mr. Richard",male,23.1,2,3,SM27598,3.50,NaN,L
409,410,0,3,"Taylor, Mr. Ernest",male,23.2,1,1,SM22098,9.05,NaN,C
185,186,0,3,"Adams, Mr. Frederick",male,23.2,2,1,SM49309,9.31,NaN,L
205,206,1,1,"Sanchez, Lady Agnes",female,23.3,0,0,SM72245,82.81,NaN,L
397,398,1,2,"Smith, Mr. Henry",male,23.3,1,0,SM74491,14.20,NaN,M
...,...,...,...,...,...,...,...,...,...,...,...,...
268,269,1,1,"Green, Lady Rose",female,69.3,1,0,SM10464,56.45,B91,M
558,559,0,2,"Perez, Mr. Frederick",male,69.7,0,0,SM26880,32.44,F27,L
424,425,0,1,"Jones, Lady Beatrice",female,69.8,0,1,SM13617,104.91,C32,C
24,25,1,1,"Lewis, Lady Harriet",female,71.1,0,0,SM39603,133.21,A93,M
392,393,1,1,"Taylor, Countess Martha",female,74.0,0,0,SM76402,139.83,NaN,M

In [59]:
df[df.Age>23 and df.Sex=="female"].sort_values("Age")

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [60]:
df[df.Age>23 & df.Sex=="female"].sort_values("Age")

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [61]:
df[(df.Age>23) & (df.Sex=="female")].sort_values("Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
205,206,1,1,"Sanchez, Lady Agnes",female,23.3,0,0,SM72245,82.81,NaN,L
373,374,1,2,"Hall, Miss Anna",female,23.6,0,0,SM54284,19.10,NaN,L
446,447,1,2,"Miller, Mrs. Ethel",female,23.7,1,2,SM62096,16.09,NaN,M
327,328,1,1,"Martinez, Countess Edith",female,23.8,2,2,SM19742,131.99,NaN,C
444,445,1,3,"Wright, Mrs. Louisa",female,23.9,1,3,SM66694,16.96,NaN,M
...,...,...,...,...,...,...,...,...,...,...,...,...
601,602,1,1,"Hernandez, Lady Alice",female,68.0,0,1,SM16572,117.19,B17,M
268,269,1,1,"Green, Lady Rose",female,69.3,1,0,SM10464,56.45,B91,M
424,425,0,1,"Jones, Lady Beatrice",female,69.8,0,1,SM13617,104.91,C32,C
24,25,1,1,"Lewis, Lady Harriet",female,71.1,0,0,SM39603,133.21,A93,M
392,393,1,1,"Taylor, Countess Martha",female,74.0,0,0,SM76402,139.83,NaN,M

In [62]:
df[(df.Age>23) & (df.Age<70) & (df.Sex=="female")].sort_values("Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
205,206,1,1,"Sanchez, Lady Agnes",female,23.3,0,0,SM72245,82.81,NaN,L
373,374,1,2,"Hall, Miss Anna",female,23.6,0,0,SM54284,19.10,NaN,L
446,447,1,2,"Miller, Mrs. Ethel",female,23.7,1,2,SM62096,16.09,NaN,M
327,328,1,1,"Martinez, Countess Edith",female,23.8,2,2,SM19742,131.99,NaN,C
222,223,1,1,"Phillips, Miss Emma",female,23.9,0,0,SM80305,106.07,A49,C
...,...,...,...,...,...,...,...,...,...,...,...,...
366,367,1,2,"Taylor, Mrs. Mary",female,64.5,0,0,SM67464,22.97,NaN,L
187,188,1,1,"Thompson, Mrs. Agnes",female,65.9,0,2,SM98117,66.97,NaN,C
601,602,1,1,"Hernandez, Lady Alice",female,68.0,0,1,SM16572,117.19,B17,M
268,269,1,1,"Green, Lady Rose",female,69.3,1,0,SM10464,56.45,B91,M
424,425,0,1,"Jones, Lady Beatrice",female,69.8,0,1,SM13617,104.91,C32,C

## manipulation of indices

In [63]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [65]:
df_1=df.set_index("PassengerId")

In [66]:
df_1.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [67]:
df.set_index(["PassengerId","Sex"])

,,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Sex,,,,,,,,,,
1,female,0,3,"Clark, Miss Mabel",22.9,2,1,SM70415,3.50,NaN,M
2,female,1,3,"Lewis, Miss Margaret",59.8,1,0,SM69589,4.35,NaN,L
3,female,1,2,"Garcia, Mrs. Anna",NaN,1,0,SM43901,14.88,NaN,C
4,female,0,2,"Parker, Mrs. Violet",27.7,0,1,SM68491,26.51,NaN,L
5,female,1,1,"Adams, Miss Rose",52.1,1,1,SM16863,65.47,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
687,female,1,1,"Jackson, Lady Florence",34.6,0,0,SM85340,100.78,B72,C
688,male,0,2,"Walker, Mr. Robert",34.6,2,0,SM95119,25.18,NaN,M
689,female,1,1,"Jackson, Lady Violet",45.7,0,0,SM87624,48.47,NaN,L
690,female,1,1,"Harris, Mrs. Gladys",43.2,0,0,SM59207,42.19,D20,M
691,female,0,3,"Green, Mrs. Clara",33.1,0,0,SM30204,5.21,NaN,M

In [68]:
df.set_index(["Sex","PassengerId"])

                    Survived  Pclass                    Name   Age  SibSp  \
Sex    PassengerId
female 1                   0       3       Clark, Miss Mabel  22.9      2
       2                   1       3    Lewis, Miss Margaret  59.8      1
       3                   1       2       Garcia, Mrs. Anna   NaN      1
       4                   0       2     Parker, Mrs. Violet  27.7      0
       5                   1       1        Adams, Miss Rose  52.1      1
...                      ...     ...                     ...   ...    ...
       687                 1       1  Jackson, Lady Florence  34.6      0
male   688                 0       2      Walker, Mr. Robert  34.6      2
female 689                 1       1    Jackson, Lady Violet  45.7      0
       690                 1       1     Harris, Mrs. Gladys  43.2      0
       691                 0       3       Green, Mrs. Clara  33.1      0

                    Parch   Ticket    Fare Cabin Embarked
Sex    PassengerId
female 1                1  SM70415    3.50   NaN        M
       2                0  SM69589    4.35   NaN        L
       3                0  SM43901   14.88   NaN        C
       4                1  SM68491   26.51   NaN        L
       5                1  SM16863   65.47   NaN        C
...                   ...      ...     ...   ...      ...
       687              0  SM85340  100.78   B72        C
male   688              0  SM95119   25.18   NaN        M
female 689              0  SM87624   48.47   NaN        L
       690              0  SM59207   42.19   D20        M
       691              0  SM30204    5.21   NaN        M

[691 rows x 10 columns]

In [69]:
df.sort_values("Sex").set_index(["Sex","PassengerId"])

                    Survived  Pclass                  Name   Age  SibSp  \
Sex    PassengerId
female 1                   0       3     Clark, Miss Mabel  22.9      2
       363                 1       2  Phillips, Mrs. Edith  17.8      1
       360                 0       3      Clark, Miss Rose  18.9      4
       358                 0       3     Davis, Miss Alice  18.9      0
       356                 1       1    Sanchez, Miss Mary  38.8      0
...                      ...     ...                   ...   ...    ...
male   369                 1       3   Collins, Mr. Thomas  16.8      0
       118                 0       3  Robinson, Mr. Thomas  15.5      3
       120                 1       3       Lopez, Mr. John  39.3      2
       122                 1       1  Campbell, Col. Edwin  43.4      0
       346                 0       3      Miller, Mr. John  29.8      0

                    Parch   Ticket   Fare Cabin Embarked
Sex    PassengerId
female 1                1  SM70415   3.50   NaN        M
       363              1  SM37483  19.38   NaN        L
       360              1  SM29278  17.31   NaN        M
       358              0  SM87283  10.37   NaN        L
       356              0  SM18200  86.62   B56        L
...                   ...      ...    ...   ...      ...
male   369              2  SM64675   9.64   NaN        M
       118              3  SM18569  16.26   NaN        L
       120              0  SM22387   6.13   NaN        C
       122              0  SM58623  81.80   A83        L
       346              2  SM40841   6.02   NaN        C

[691 rows x 10 columns]