In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../datasets/SS_meridian.csv")

In [3]:
## Apply, map and applymap methods

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [6]:
df.Pclass.apply(float)

0      3.0
1      3.0
2      2.0
3      2.0
4      1.0
      ...
686    1.0
687    2.0
688    1.0
689    1.0
690    3.0
Name: Pclass, Length: 691, dtype: float64

In [11]:
df.Age.fillna(value=df.Age.mean()).apply(int)

0      22
1      59
2      31
3      27
4      52
       ..
686    34
687    34
688    45
689    43
690    33
Name: Age, Length: 691, dtype: int64

In [12]:
df.Age.fillna(value=df.Age.mean()).apply(round)

0      23
1      60
2      32
3      28
4      52
       ..
686    35
687    35
688    46
689    43
690    33
Name: Age, Length: 691, dtype: int64

In [13]:
def extract_last_5(value):
    return value[-5:]

In [14]:
extract_last_5("SM69589")

'69589'

In [15]:
extract_last_5("SM16863")

'16863'

In [16]:
df.Ticket.apply(extract_last_5)

0      70415
1      69589
2      43901
3      68491
4      16863
       ...
686    85340
687    95119
688    87624
689    59207
690    30204
Name: Ticket, Length: 691, dtype: object

In [21]:
def get_last_name(name):
    return name.split(",")[0]

In [22]:
get_last_name("Clark, Miss Mabel")

'Clark'

In [23]:
get_last_name("Adams, Miss Rose")

'Adams'

In [24]:
df.Name.apply(get_last_name)

0        Clark
1        Lewis
2       Garcia
3       Parker
4        Adams
        ...
686    Jackson
687     Walker
688    Jackson
689     Harris
690      Green
Name: Name, Length: 691, dtype: object

In [30]:
def get_other_names(name):
    return name.split(",")[-1].strip()

In [31]:
get_other_names("Clark, Miss Mabel")

'Miss Mabel'

In [32]:
df.Name.apply( get_other_names)

0         Miss Mabel
1      Miss Margaret
2          Mrs. Anna
3        Mrs. Violet
4          Miss Rose
           ...
686    Lady Florence
687       Mr. Robert
688      Lady Violet
689      Mrs. Gladys
690       Mrs. Clara
Name: Name, Length: 691, dtype: object

In [33]:
df.Sex

0      female
1      female
2      female
3      female
4      female
        ...
686    female
687      male
688    female
689    female
690    female
Name: Sex, Length: 691, dtype: object

In [34]:
df.Sex.map( {"female":"F","male":"M"})

0      F
1      F
2      F
3      F
4      F
      ..
686    F
687    M
688    F
689    F
690    F
Name: Sex, Length: 691, dtype: object

In [35]:
df.Name.map(get_last_name)

0        Clark
1        Lewis
2       Garcia
3       Parker
4        Adams
        ...
686    Jackson
687     Walker
688    Jackson
689     Harris
690      Green
Name: Name, Length: 691, dtype: object

In [38]:
df.Sex

0      female
1      female
2      female
3      female
4      female
        ...
686    female
687      male
688    female
689    female
690    female
Name: Sex, Length: 691, dtype: object

In [36]:
pd.get_dummies(df.Sex )

     female   male
0      True  False
1      True  False
2      True  False
3      True  False
4      True  False
..      ...    ...
686    True  False
687   False   True
688    True  False
689    True  False
690    True  False

[691 rows x 2 columns]

In [40]:
import numpy as np
a=np.array([1,0,1,0,0,1])
b=np.array([0,1,0,1,1,0])

In [41]:
np.corrcoef(a,b)

array([[ 1., -1.],
       [-1.,  1.]])

In [42]:
pd.get_dummies(df.Sex ,drop_first=True)

      male
0    False
1    False
2    False
3    False
4    False
..     ...
686  False
687   True
688  False
689  False
690  False

[691 rows x 1 columns]