In [2]:
import pandas as pd
import numpy as np

In [23]:
df=pd.DataFrame({"A":[np.nan,10,47,np.nan,10,67,np.nan,np.nan],"b":range(8)})

In [6]:
df

      A  b
0   NaN  0
1  10.0  1
2  47.0  2
3   NaN  3
4  35.0  4
5  67.0  5
6   NaN  6
7   NaN  7

In [13]:
df.A=df.A.fillna(method="ffill")

C:\Users\georg\AppData\Local\Temp\ipykernel_32116\2216623857.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.A=df.A.fillna(method="ffill")

In [14]:
df

      A  b
0   NaN  0
1  10.0  1
2  47.0  2
3  47.0  3
4  35.0  4
5  67.0  5
6  67.0  6
7  67.0  7

In [15]:
df.A.fillna(method="bfill")

C:\Users\georg\AppData\Local\Temp\ipykernel_32116\3043632701.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.A.fillna(method="bfill")

0    10.0
1    10.0
2    47.0
3    47.0
4    35.0
5    67.0
6    67.0
7    67.0
Name: A, dtype: float64

In [24]:
df

      A  b
0   NaN  0
1  10.0  1
2  47.0  2
3   NaN  3
4  10.0  4
5  67.0  5
6   NaN  6
7   NaN  7

In [18]:
df.A.fillna(value=df.A.mean())

0    39.75
1    10.00
2    47.00
3    39.75
4    35.00
5    67.00
6    39.75
7    39.75
Name: A, dtype: float64

In [19]:
df.A.fillna(value=df.A.median())

0    41.0
1    10.0
2    47.0
3    41.0
4    35.0
5    67.0
6    41.0
7    41.0
Name: A, dtype: float64

In [34]:
df.A.fillna(value=df.A.mode()[0])

0    10.0
1    10.0
2    47.0
3    10.0
4    10.0
5    67.0
6    10.0
7    10.0
Name: A, dtype: float64

In [21]:
df

      A  b
0   NaN  0
1  10.0  1
2  47.0  2
3   NaN  3
4  35.0  4
5  67.0  5
6   NaN  6
7   NaN  7

In [25]:
df.A.mode()

0    10.0
Name: A, dtype: float64

In [32]:
df.A.mode()

0    10.0
Name: A, dtype: float64

In [33]:
df.A.mode()[0]

np.float64(10.0)

## Data Transformation

In [44]:
df=pd.read_csv("../datasets/SS_meridian.csv")

In [45]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C