In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"week1":np.random.randint(1,20,7),"week 2":np.random.randint(1,20,7)})

In [3]:
df

   week1  week 2
0      5       1
1      5      19
2     16      12
3      1      16
4      8       5
5      5      18
6     16       6

In [4]:
df.head()

   week1  week 2
0      5       1
1      5      19
2     16      12
3      1      16
4      8       5

In [5]:
df.tail()

   week1  week 2
2     16      12
3      1      16
4      8       5
5      5      18
6     16       6

In [6]:
df.head(2)

   week1  week 2
0      5       1
1      5      19

In [7]:
df.sample()

   week1  week 2
4      8       5

In [8]:
df.sample(3)

   week1  week 2
6     16       6
2     16      12
0      5       1

In [9]:
df.sample(3)

   week1  week 2
0      5       1
2     16      12
5      5      18

In [10]:
list(df.index)

[0, 1, 2, 3, 4, 5, 6]

In [11]:
df.columns

Index(['week1', 'week 2'], dtype='object')

In [12]:
df.index=range(2,9)

In [13]:
df

   week1  week 2
2      5       1
3      5      19
4     16      12
5      1      16
6      8       5
7      5      18
8     16       6

In [14]:
df.loc[2]

week1     5
week 2    1
Name: 2, dtype: int32

In [15]:
df.iloc[2]

week1     16
week 2    12
Name: 4, dtype: int32

In [16]:
df.week1

2     5
3     5
4    16
5     1
6     8
7     5
8    16
Name: week1, dtype: int32

In [17]:
df["week1"]

2     5
3     5
4    16
5     1
6     8
7     5
8    16
Name: week1, dtype: int32

In [18]:
df

   week1  week 2
2      5       1
3      5      19
4     16      12
5      1      16
6      8       5
7      5      18
8     16       6

In [19]:
df["week 2"]

2     1
3    19
4    12
5    16
6     5
7    18
8     6
Name: week 2, dtype: int32

In [20]:
df.columns =["week1","week2"]

In [21]:
df

   week1  week2
2      5      1
3      5     19
4     16     12
5      1     16
6      8      5
7      5     18
8     16      6

In [22]:
df["total"]=df.week1+ df.week2

In [23]:
df

   week1  week2  total
2      5      1      6
3      5     19     24
4     16     12     28
5      1     16     17
6      8      5     13
7      5     18     23
8     16      6     22

In [24]:
df["week1%"]= df.week1/df["total"]*100

In [25]:
df

   week1  week2  total     week1%
2      5      1      6  83.333333
3      5     19     24  20.833333
4     16     12     28  57.142857
5      1     16     17   5.882353
6      8      5     13  61.538462
7      5     18     23  21.739130
8     16      6     22  72.727273

In [26]:
df["dchdc"]=np.arange(7)*100

In [27]:
df

   week1  week2  total     week1%  dchdc
2      5      1      6  83.333333      0
3      5     19     24  20.833333    100
4     16     12     28  57.142857    200
5      1     16     17   5.882353    300
6      8      5     13  61.538462    400
7      5     18     23  21.739130    500
8     16      6     22  72.727273    600

In [28]:
df.drop("dchdc")

KeyError: "['dchdc'] not found in axis"

In [ ]:
df.drop("dchdc",axis=1)

In [30]:
df.drop("dchdc",axis="columns",inplace=True)

In [ ]:
df.drop("dchdc",axis=1,inplace=True)

In [ ]:
df

In [31]:
df1=pd.read_csv("student.csv")

In [32]:
df1.head()

,STUDENT ID,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,COURSE ID,GRADE
0,STUDENT1,2,2,3,3,1,2,2,1,1,...,1,1,3,2,1,2,1,1,1,1
1,STUDENT2,2,2,3,3,1,2,2,1,1,...,1,1,3,2,3,2,2,3,1,1
2,STUDENT3,2,2,2,3,2,2,2,2,4,...,1,1,2,2,1,1,2,2,1,1
3,STUDENT4,1,1,1,3,1,2,1,2,1,...,1,2,3,2,2,1,3,2,1,1
4,STUDENT5,2,2,1,3,2,2,1,3,1,...,2,1,2,2,2,1,2,2,1,1

In [33]:
df1.shape

(145, 33)

In [34]:
df1

,STUDENT ID,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,COURSE ID,GRADE
0,STUDENT1,2,2,3,3,1,2,2,1,1,...,1,1,3,2,1,2,1,1,1,1
1,STUDENT2,2,2,3,3,1,2,2,1,1,...,1,1,3,2,3,2,2,3,1,1
2,STUDENT3,2,2,2,3,2,2,2,2,4,...,1,1,2,2,1,1,2,2,1,1
3,STUDENT4,1,1,1,3,1,2,1,2,1,...,1,2,3,2,2,1,3,2,1,1
4,STUDENT5,2,2,1,3,2,2,1,3,1,...,2,1,2,2,2,1,2,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,STUDENT141,2,1,2,3,1,1,2,1,1,...,1,1,2,1,2,1,3,3,9,5
141,STUDENT142,1,1,2,4,2,2,2,1,4,...,1,1,3,2,2,1,5,3,9,5
142,STUDENT143,1,1,1,4,2,2,2,1,1,...,1,1,3,3,2,1,4,3,9,1
143,STUDENT144,2,1,2,4,1,1,1,5,2,...,2,1,2,1,2,1,5,3,9,4
144,STUDENT145,1,1,1,5,2,2,2,3,1,...,2,1,3,2,3,1,5,4,9,3

In [35]:
df1.iloc[1]

STUDENT ID    STUDENT2
1                    2
2                    2
3                    3
4                    3
5                    1
6                    2
7                    2
8                    1
9                    1
10                   1
11                   2
12                   3
13                   2
14                   1
15                   2
16                   1
17                   2
18                   2
19                   2
20                   1
21                   1
22                   1
23                   1
24                   1
25                   3
26                   2
27                   3
28                   2
29                   2
30                   3
COURSE ID            1
GRADE                1
Name: 1, dtype: object