In [3]:
import pandas as pd
import numpy as np

In [4]:
employees = pd.DataFrame({
    'emp_id':  [101, 102, 103, 104, 105, 106],
    'name':    ['Ada', 'Bola', 'Chidi', 'Dayo', 'Ebere', 'Femi'],
    'dept_id': [1,    2,     2,      3,     np.nan, 99],
    'city':    ['Lagos', 'Abuja', 'Lagos', 'Port Harcourt', 'Kano', 'Ibadan'],
    'salary':  [450000, 520000, 480000, 600000, 390000, 410000],
})

departments = pd.DataFrame({
    'dept_id':   [1, 2, 3, 4, np.nan],
    'dept_name': ['Engineering', 'Data Science', 'Product', 'Marketing', 'Unassigned'],
    'budget':    [5_000_000, 8_000_000, 6_000_000, 3_000_000, 500_000],
    'manager':   ['Tunde', 'Ngozi', 'Sade', 'Kola', 'HR Pool'],
})

In [5]:
employees

   emp_id   name  dept_id           city  salary
0     101    Ada      1.0          Lagos  450000
1     102   Bola      2.0          Abuja  520000
2     103  Chidi      2.0          Lagos  480000
3     104   Dayo      3.0  Port Harcourt  600000
4     105  Ebere      NaN           Kano  390000
5     106   Femi     99.0         Ibadan  410000

In [6]:
departments

   dept_id     dept_name   budget  manager
0      1.0   Engineering  5000000    Tunde
1      2.0  Data Science  8000000    Ngozi
2      3.0       Product  6000000     Sade
3      4.0     Marketing  3000000     Kola
4      NaN    Unassigned   500000  HR Pool

In [7]:
pd.merge( employees,departments)

,emp_id,name,dept_id,city,salary,dept_name,budget,manager
0,101,Ada,1.0,Lagos,450000,Engineering,5000000,Tunde
1,102,Bola,2.0,Abuja,520000,Data Science,8000000,Ngozi
2,103,Chidi,2.0,Lagos,480000,Data Science,8000000,Ngozi
3,104,Dayo,3.0,Port Harcourt,600000,Product,6000000,Sade
4,105,Ebere,NaN,Kano,390000,Unassigned,500000,HR Pool

In [8]:
employees = pd.DataFrame({
    'emp_id':  [101, 102, 103, 104, 105, 106],
    'name':    ['Ada', 'Bola', 'Chidi', 'Dayo', 'Ebere', 'Femi'],
    'deptId': [1,    2,     2,      3,     np.nan, 99],
    'city':    ['Lagos', 'Abuja', 'Lagos', 'Port Harcourt', 'Kano', 'Ibadan'],
    'salary':  [450000, 520000, 480000, 600000, 390000, 410000],
})

departments = pd.DataFrame({
    'dept_id':   [1, 2, 3, 4, np.nan],
    'dept_name': ['Engineering', 'Data Science', 'Product', 'Marketing', 'Unassigned'],
    'budget':    [5_000_000, 8_000_000, 6_000_000, 3_000_000, 500_000],
    'manager':   ['Tunde', 'Ngozi', 'Sade', 'Kola', 'HR Pool'],
})

In [10]:
pd.merge( employees,departments,left_on="deptId",right_on="dept_id")

,emp_id,name,deptId,city,salary,dept_id,dept_name,budget,manager
0,101,Ada,1.0,Lagos,450000,1.0,Engineering,5000000,Tunde
1,102,Bola,2.0,Abuja,520000,2.0,Data Science,8000000,Ngozi
2,103,Chidi,2.0,Lagos,480000,2.0,Data Science,8000000,Ngozi
3,104,Dayo,3.0,Port Harcourt,600000,3.0,Product,6000000,Sade
4,105,Ebere,NaN,Kano,390000,NaN,Unassigned,500000,HR Pool

In [12]:
pd.merge( employees,departments,left_on="deptId",right_on="dept_id")["dept_name"].unique()

array(['Engineering', 'Data Science', 'Product', 'Unassigned'],
      dtype=object)

In [20]:
pd.merge( employees,departments,left_on="deptId",right_on="dept_id")["dept_id"].isna()

0    False
1    False
2    False
3    False
4     True
Name: dept_id, dtype: bool

In [16]:
df_assigned_values=~(pd.merge( employees,departments,left_on="deptId",right_on="dept_id")["dept_id"].isna())

In [21]:
df_assigned_values

0     True
1     True
2     True
3     True
4    False
Name: dept_id, dtype: bool

In [24]:
pd.merge( employees,departments,left_on="deptId",right_on="dept_id")[df_assigned_values]["dept_name"].unique()

array(['Engineering', 'Data Science', 'Product'], dtype=object)

In [27]:
employees = pd.DataFrame({
    'emp_id':  [101, 102, 103, 104, 105, 106],
    'name':    ['Ada', 'Bola', 'Chidi', 'Dayo', 'Ebere', 'Femi'],
    'dept_id': [1,    2,     2,      3,     np.nan, 99],
    'city':    ['Lagos', 'Abuja', 'Lagos', 'Port Harcourt', 'Kano', 'Ibadan'],
    'salary':  [450000, 520000, 480000, 600000, 390000, 410000],
})

departments = pd.DataFrame({
    'dept_id':   [1, 2, 3, 4, np.nan],
    'dept_name': ['Engineering', 'Data Science', 'Product', 'Marketing', 'Unassigned'],
    'budget':    [5_000_000, 8_000_000, 6_000_000, 3_000_000, 500_000],
    'manager':   ['Tunde', 'Ngozi', 'Sade', 'Kola', 'HR Pool'],
})

In [25]:
employees

   emp_id   name  deptId           city  salary
0     101    Ada     1.0          Lagos  450000
1     102   Bola     2.0          Abuja  520000
2     103  Chidi     2.0          Lagos  480000
3     104   Dayo     3.0  Port Harcourt  600000
4     105  Ebere     NaN           Kano  390000
5     106   Femi    99.0         Ibadan  410000

In [26]:
departments

   dept_id     dept_name   budget  manager
0      1.0   Engineering  5000000    Tunde
1      2.0  Data Science  8000000    Ngozi
2      3.0       Product  6000000     Sade
3      4.0     Marketing  3000000     Kola
4      NaN    Unassigned   500000  HR Pool

In [29]:
pd.merge(employees,departments,how="left")

,emp_id,name,dept_id,city,salary,dept_name,budget,manager
0,101,Ada,1.0,Lagos,450000,Engineering,5000000.0,Tunde
1,102,Bola,2.0,Abuja,520000,Data Science,8000000.0,Ngozi
2,103,Chidi,2.0,Lagos,480000,Data Science,8000000.0,Ngozi
3,104,Dayo,3.0,Port Harcourt,600000,Product,6000000.0,Sade
4,105,Ebere,NaN,Kano,390000,Unassigned,500000.0,HR Pool
5,106,Femi,99.0,Ibadan,410000,NaN,NaN,NaN

In [30]:
pd.merge(departments,employees,how="right")

,dept_id,dept_name,budget,manager,emp_id,name,city,salary
0,1.0,Engineering,5000000.0,Tunde,101,Ada,Lagos,450000
1,2.0,Data Science,8000000.0,Ngozi,102,Bola,Abuja,520000
2,2.0,Data Science,8000000.0,Ngozi,103,Chidi,Lagos,480000
3,3.0,Product,6000000.0,Sade,104,Dayo,Port Harcourt,600000
4,NaN,Unassigned,500000.0,HR Pool,105,Ebere,Kano,390000
5,99.0,NaN,NaN,NaN,106,Femi,Ibadan,410000

In [38]:
pd.merge( departments,employees,how="outer")#[["name","city","salary","emp_id"]]

,dept_id,dept_name,budget,manager,emp_id,name,city,salary
0,1.0,Engineering,5000000.0,Tunde,101.0,Ada,Lagos,450000.0
1,2.0,Data Science,8000000.0,Ngozi,102.0,Bola,Abuja,520000.0
2,2.0,Data Science,8000000.0,Ngozi,103.0,Chidi,Lagos,480000.0
3,3.0,Product,6000000.0,Sade,104.0,Dayo,Port Harcourt,600000.0
4,4.0,Marketing,3000000.0,Kola,NaN,NaN,NaN,NaN
5,99.0,NaN,NaN,NaN,106.0,Femi,Ibadan,410000.0
6,NaN,Unassigned,500000.0,HR Pool,105.0,Ebere,Kano,390000.0

In [39]:
pd.merge( departments,employees,how="cross")

,dept_id_x,dept_name,budget,manager,emp_id,name,dept_id_y,city,salary
0,1.0,Engineering,5000000,Tunde,101,Ada,1.0,Lagos,450000
1,1.0,Engineering,5000000,Tunde,102,Bola,2.0,Abuja,520000
2,1.0,Engineering,5000000,Tunde,103,Chidi,2.0,Lagos,480000
3,1.0,Engineering,5000000,Tunde,104,Dayo,3.0,Port Harcourt,600000
4,1.0,Engineering,5000000,Tunde,105,Ebere,NaN,Kano,390000
5,1.0,Engineering,5000000,Tunde,106,Femi,99.0,Ibadan,410000
6,2.0,Data Science,8000000,Ngozi,101,Ada,1.0,Lagos,450000
7,2.0,Data Science,8000000,Ngozi,102,Bola,2.0,Abuja,520000
8,2.0,Data Science,8000000,Ngozi,103,Chidi,2.0,Lagos,480000
9,2.0,Data Science,8000000,Ngozi,104,Dayo,3.0,Port Harcourt,600000
10,2.0,Data Science,8000000,Ngozi,105,Ebere,NaN,Kano,390000
11,2.0,Data Science,8000000,Ngozi,106,Femi,99.0,Ibadan,410000
12,3.0,Product,6000000,Sade,101,Ada,1.0,Lagos,450000
13,3.0,Product,6000000,Sade,102,Bola,2.0,Abuja,520000
14,3.0,Product,6000000,Sade,103,Chidi,2.0,Lagos,480000
15,3.0,Product,6000000,Sade,104,Dayo,3.0,Port Harcourt,600000
16,3.0,Product,6000000,Sade,105,Ebere,NaN,Kano,390000
17,3.0,Product,6000000,Sade,106,Femi,99.0,Ibadan,410000
18,4.0,Marketing,3000000,Kola,101,Ada,1.0,Lagos,450000
19,4.0,Marketing,3000000,Kola,102,Bola,2.0,Abuja,520000
20,4.0,Marketing,3000000,Kola,103,Chidi,2.0,Lagos,480000
21,4.0,Marketing,3000000,Kola,104,Dayo,3.0,Port Harcourt,600000
22,4.0,Marketing,3000000,Kola,105,Ebere,NaN,Kano,390000
23,4.0,Marketing,3000000,Kola,106,Femi,99.0,Ibadan,410000
24,NaN,Unassigned,500000,HR Pool,101,Ada,1.0,Lagos,450000
25,NaN,Unassigned,500000,HR Pool,102,Bola,2.0,Abuja,520000
26,NaN,Unassigned,500000,HR Pool,103,Chidi,2.0,Lagos,480000
27,NaN,Unassigned,500000,HR Pool,104,Dayo,3.0,Port Harcourt,600000
28,NaN,Unassigned,500000,HR Pool,105,Ebere,NaN,Kano,390000
29,NaN,Unassigned,500000,HR Pool,106,Femi,99.0,Ibadan,410000

In [40]:
pd.merge( employees,employees,how="cross")

,emp_id_x,name_x,dept_id_x,city_x,salary_x,emp_id_y,name_y,dept_id_y,city_y,salary_y
0,101,Ada,1.0,Lagos,450000,101,Ada,1.0,Lagos,450000
1,101,Ada,1.0,Lagos,450000,102,Bola,2.0,Abuja,520000
2,101,Ada,1.0,Lagos,450000,103,Chidi,2.0,Lagos,480000
3,101,Ada,1.0,Lagos,450000,104,Dayo,3.0,Port Harcourt,600000
4,101,Ada,1.0,Lagos,450000,105,Ebere,NaN,Kano,390000
5,101,Ada,1.0,Lagos,450000,106,Femi,99.0,Ibadan,410000
6,102,Bola,2.0,Abuja,520000,101,Ada,1.0,Lagos,450000
7,102,Bola,2.0,Abuja,520000,102,Bola,2.0,Abuja,520000
8,102,Bola,2.0,Abuja,520000,103,Chidi,2.0,Lagos,480000
9,102,Bola,2.0,Abuja,520000,104,Dayo,3.0,Port Harcourt,600000
10,102,Bola,2.0,Abuja,520000,105,Ebere,NaN,Kano,390000
11,102,Bola,2.0,Abuja,520000,106,Femi,99.0,Ibadan,410000
12,103,Chidi,2.0,Lagos,480000,101,Ada,1.0,Lagos,450000
13,103,Chidi,2.0,Lagos,480000,102,Bola,2.0,Abuja,520000
14,103,Chidi,2.0,Lagos,480000,103,Chidi,2.0,Lagos,480000
15,103,Chidi,2.0,Lagos,480000,104,Dayo,3.0,Port Harcourt,600000
16,103,Chidi,2.0,Lagos,480000,105,Ebere,NaN,Kano,390000
17,103,Chidi,2.0,Lagos,480000,106,Femi,99.0,Ibadan,410000
18,104,Dayo,3.0,Port Harcourt,600000,101,Ada,1.0,Lagos,450000
19,104,Dayo,3.0,Port Harcourt,600000,102,Bola,2.0,Abuja,520000
20,104,Dayo,3.0,Port Harcourt,600000,103,Chidi,2.0,Lagos,480000
21,104,Dayo,3.0,Port Harcourt,600000,104,Dayo,3.0,Port Harcourt,600000
22,104,Dayo,3.0,Port Harcourt,600000,105,Ebere,NaN,Kano,390000
23,104,Dayo,3.0,Port Harcourt,600000,106,Femi,99.0,Ibadan,410000
24,105,Ebere,NaN,Kano,390000,101,Ada,1.0,Lagos,450000
25,105,Ebere,NaN,Kano,390000,102,Bola,2.0,Abuja,520000
26,105,Ebere,NaN,Kano,390000,103,Chidi,2.0,Lagos,480000
27,105,Ebere,NaN,Kano,390000,104,Dayo,3.0,Port Harcourt,600000
28,105,Ebere,NaN,Kano,390000,105,Ebere,NaN,Kano,390000
29,105,Ebere,NaN,Kano,390000,106,Femi,99.0,Ibadan,410000
30,106,Femi,99.0,Ibadan,410000,101,Ada,1.0,Lagos,450000
31,106,Femi,99.0,Ibadan,410000,102,Bola,2.0,Abuja,520000
32,106,Femi,99.0,Ibadan,410000,103,Chidi,2.0,Lagos,480000
33,106,Femi,99.0,Ibadan,410000,104,Dayo,3.0,Port Harcourt,600000
34,106,Femi,99.0,Ibadan,410000,105,Ebere,NaN,Kano,390000
35,106,Femi,99.0,Ibadan,410000,106,Femi,99.0,Ibadan,410000

## Mini project

In [41]:
import matplotlib.pyplot as plt
import seaborn as sns

# Set random seed for reproducibility
np.random.seed(42)

# Create sales data
sales_data = {
    'date': pd.date_range(start='2023-01-01', periods=100, freq='D'),
    'store': np.random.choice(['A', 'B', 'C', 'D'], size=100),
    'product': np.random.choice(['Widget', 'Gadget', 'Tool', 'Device'], size=100),
    'sales': np.random.randint(10, 100, size=100),
    'units': np.random.randint(1, 10, size=100),
    'promotion': np.random.choice([True, False], size=100),
}

sales_df = pd.DataFrame(sales_data)
sales_df['month'] = sales_df['date'].dt.month_name()
sales_df['day'] = sales_df['date'].dt.day_name()

# Create customer data
customers = {
    'customer_id': range(1, 51),
    'store': np.random.choice(['A', 'B', 'C', 'D', 'E'], size=50),
    'age': np.random.randint(18, 80, size=50),
    'gender': np.random.choice(['M', 'F', 'Other'], size=50, p=[0.48, 0.48, 0.04]),
    'membership_level': np.random.choice(['Bronze', 'Silver', 'Gold', 'Platinum'], size=50),
    'signup_date': pd.date_range(start='2022-01-01', periods=50)
}

customer_df = pd.DataFrame(customers)

# Create transaction data that links to customers
transactions = {
    'transaction_id': range(1, 201),
    'customer_id': np.random.choice(range(1, 51), size=200),
    'date': pd.date_range(start='2023-01-01', periods=200, freq='H'),
    'amount': np.random.uniform(10, 500, size=200).round(2),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Food', 'Home', 'Beauty'], size=200)
}

transaction_df = pd.DataFrame(transactions)

# Create employee data for each store
employees = {
    'employee_id': range(1, 31),
    'store': np.random.choice(['A', 'B', 'C', 'D'], size=30),
    'department': np.random.choice(['Sales', 'Management', 'Support', 'Logistics'], size=30),
    'hire_date': pd.date_range(start='2020-01-01', periods=30, freq='W'),
    'salary': np.random.normal(50000, 15000, size=30).round(2)
}

employee_df = pd.DataFrame(employees)

# Create store information data
store_info = pd.DataFrame({
    'store': ['A', 'B', 'C', 'D', 'E'],
    'location': ['North', 'South', 'East', 'West', 'Central'],
    'size_sqft': [15000, 8000, 5000, 12000, 10000],
    'opening_date': pd.to_datetime(['2018-03-15', '2019-06-25', '2020-11-10', '2017-01-05', '2021-08-30']),
    'manager_id': [5, 12, 18, 24, None]  # Note: Store E has no manager ID
})

# Optional: Save to CSV for reference
sales_df.to_csv('sales_data.csv', index=False)
customer_df.to_csv('customer_data.csv', index=False)
transaction_df.to_csv('transaction_data.csv', index=False)
employee_df.to_csv('employee_data.csv', index=False)
store_info.to_csv('store_info.csv', index=False)

# Display first few rows of each dataset
print("Sales Data:")
print(sales_df.head(3))
print("\nCustomer Data:")
print(customer_df.head(3))
print("\nTransaction Data:")
print(transaction_df.head(3))
print("\nEmployee Data:")
print(employee_df.head(3))
print("\nStore Information:")
print(store_info.head())

Sales Data:
        date store product  sales  units  promotion    month      day
0 2023-01-01     C    Tool     72      7       True  January   Sunday
1 2023-01-02     D  Gadget     61      2      False  January   Monday
2 2023-01-03     A  Gadget     13      8       True  January  Tuesday

Customer Data:
   customer_id store  age gender membership_level signup_date
0            1     B   62      F             Gold  2022-01-01
1            2     E   21      M             Gold  2022-01-02
2            3     B   33      M           Silver  2022-01-03

Transaction Data:
   transaction_id  customer_id                date  amount product_category
0               1           26 2023-01-01 00:00:00   47.17         Clothing
1               2           19 2023-01-01 01:00:00   73.15             Food
2               3           39 2023-01-01 02:00:00   72.74             Home

Employee Data:
   employee_id store department  hire_date    salary
0            1     A  Logistics 2020-01-05  42798.16
1            2     A      Sales 2020-01-12  84477.03
2            3     A    Support 2020-01-19  30979.68

Store Information:
  store location  size_sqft opening_date  manager_id
0     A    North      15000   2018-03-15         5.0
1     B    South       8000   2019-06-25        12.0
2     C     East       5000   2020-11-10        18.0
3     D     West      12000   2017-01-05        24.0
4     E  Central      10000   2021-08-30         NaN

C:\Users\georg\AppData\Local\Temp\ipykernel_5192\4066415927.py:37: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  'date': pd.date_range(start='2023-01-01', periods=200, freq='H'),

In [42]:
sales_df.head(3)

        date store product  sales  units  promotion    month      day
0 2023-01-01     C    Tool     72      7       True  January   Sunday
1 2023-01-02     D  Gadget     61      2      False  January   Monday
2 2023-01-03     A  Gadget     13      8       True  January  Tuesday

In [43]:
customer_df.head(3)

   customer_id store  age gender membership_level signup_date
0            1     B   62      F             Gold  2022-01-01
1            2     E   21      M             Gold  2022-01-02
2            3     B   33      M           Silver  2022-01-03

In [44]:
transaction_df.head(3)

   transaction_id  customer_id                date  amount product_category
0               1           26 2023-01-01 00:00:00   47.17         Clothing
1               2           19 2023-01-01 01:00:00   73.15             Food
2               3           39 2023-01-01 02:00:00   72.74             Home

In [45]:
employee_df.head(3)

   employee_id store department  hire_date    salary
0            1     A  Logistics 2020-01-05  42798.16
1            2     A      Sales 2020-01-12  84477.03
2            3     A    Support 2020-01-19  30979.68

In [46]:
store_info.head()

  store location  size_sqft opening_date  manager_id
0     A    North      15000   2018-03-15         5.0
1     B    South       8000   2019-06-25        12.0
2     C     East       5000   2020-11-10        18.0
3     D     West      12000   2017-01-05        24.0
4     E  Central      10000   2021-08-30         NaN

Q1: Perform an inner join between the store_info and employee_df dataframes on the 'store' column. How many employees work in each store location?

In [47]:
store_info.head(1)

  store location  size_sqft opening_date  manager_id
0     A    North      15000   2018-03-15         5.0

In [48]:
employee_df.head(1)

   employee_id store department  hire_date    salary
0            1     A  Logistics 2020-01-05  42798.16

In [ ]:
pd.merge(employee_df,store_info)

In [50]:
pd.merge(employee_df,store_info,on="store")

,employee_id,store,department,hire_date,salary,location,size_sqft,opening_date,manager_id
0,1,A,Logistics,2020-01-05,42798.16,North,15000,2018-03-15,5.0
1,2,A,Sales,2020-01-12,84477.03,North,15000,2018-03-15,5.0
2,3,A,Support,2020-01-19,30979.68,North,15000,2018-03-15,5.0
3,4,C,Support,2020-01-26,30062.81,East,5000,2020-11-10,18.0
4,5,B,Logistics,2020-02-02,74824.68,South,8000,2019-06-25,12.0
5,6,A,Support,2020-02-09,39435.81,North,15000,2018-03-15,5.0
6,7,A,Management,2020-02-16,35829.64,North,15000,2018-03-15,5.0
7,8,B,Management,2020-02-23,84543.68,South,8000,2019-06-25,12.0
8,9,A,Support,2020-03-01,64785.84,North,15000,2018-03-15,5.0
9,10,D,Support,2020-03-08,41083.03,West,12000,2017-01-05,24.0
10,11,B,Logistics,2020-03-15,53262.62,South,8000,2019-06-25,12.0
11,12,B,Management,2020-03-22,79188.07,South,8000,2019-06-25,12.0
12,13,B,Management,2020-03-29,60374.31,South,8000,2019-06-25,12.0
13,14,D,Sales,2020-04-05,69292.23,West,12000,2017-01-05,24.0
14,15,B,Logistics,2020-04-12,62072.05,South,8000,2019-06-25,12.0
15,16,D,Sales,2020-04-19,63953.80,West,12000,2017-01-05,24.0
16,17,B,Management,2020-04-26,50596.13,South,8000,2019-06-25,12.0
17,18,C,Logistics,2020-05-03,50170.23,East,5000,2020-11-10,18.0
18,19,A,Support,2020-05-10,54005.76,North,15000,2018-03-15,5.0
19,20,C,Logistics,2020-05-17,61016.79,East,5000,2020-11-10,18.0
20,21,A,Support,2020-05-24,45750.27,North,15000,2018-03-15,5.0
21,22,D,Support,2020-05-31,51830.81,West,12000,2017-01-05,24.0
22,23,C,Logistics,2020-06-07,45344.82,East,5000,2020-11-10,18.0
23,24,B,Support,2020-06-14,51735.27,South,8000,2019-06-25,12.0
24,25,A,Sales,2020-06-21,31235.06,North,15000,2018-03-15,5.0
25,26,A,Management,2020-06-28,89089.66,North,15000,2018-03-15,5.0
26,27,C,Support,2020-07-05,39005.90,East,5000,2020-11-10,18.0
27,28,D,Sales,2020-07-12,44578.09,West,12000,2017-01-05,24.0
28,29,C,Support,2020-07-19,37711.03,East,5000,2020-11-10,18.0
29,30,D,Management,2020-07-26,59235.63,West,12000,2017-01-05,24.0

In [51]:
pd.merge(employee_df,store_info).groupby("location")["employee_id"].count()

location
East      6
North    10
South     8
West      6
Name: employee_id, dtype: int64

Q2: Perform a left join between customer_df and transaction_df (on customer_id) to find all customers and their transactions. Identify how many customers have not made any transactions.

In [52]:
transaction_df.head(1)

   transaction_id  customer_id       date  amount product_category
0               1           26 2023-01-01   47.17         Clothing

In [53]:
customer_df.head(1)

   customer_id store  age gender membership_level signup_date
0            1     B   62      F             Gold  2022-01-01

In [54]:
pd.merge(customer_df,transaction_df,how="left")

,customer_id,store,age,gender,membership_level,signup_date,transaction_id,date,amount,product_category
0,1,B,62,F,Gold,2022-01-01,14.0,2023-01-01 13:00:00,30.03,Home
1,1,B,62,F,Gold,2022-01-01,44.0,2023-01-02 19:00:00,133.69,Food
2,1,B,62,F,Gold,2022-01-01,93.0,2023-01-04 20:00:00,485.04,Clothing
3,1,B,62,F,Gold,2022-01-01,110.0,2023-01-05 13:00:00,309.20,Clothing
4,1,B,62,F,Gold,2022-01-01,132.0,2023-01-06 11:00:00,482.86,Electronics
...,...,...,...,...,...,...,...,...,...,...
196,50,E,79,F,Silver,2022-02-19,7.0,2023-01-01 06:00:00,99.12,Electronics
197,50,E,79,F,Silver,2022-02-19,63.0,2023-01-03 14:00:00,396.69,Electronics
198,50,E,79,F,Silver,2022-02-19,89.0,2023-01-04 16:00:00,211.09,Food
199,50,E,79,F,Silver,2022-02-19,148.0,2023-01-07 03:00:00,266.30,Food
200,50,E,79,F,Silver,2022-02-19,169.0,2023-01-08 00:00:00,78.24,Clothing

In [55]:
pd.merge(customer_df,transaction_df,how="left")["transaction_id"].isna().sum()

np.int64(1)

In [56]:
pd.merge(customer_df,transaction_df,how="left")["date"].isna().sum()

np.int64(1)

In [57]:
pd.merge(customer_df,transaction_df,how="left")["amount"].isna().sum()

np.int64(1)

In [59]:
pd.merge(customer_df,transaction_df,how="left")["product_category"].isna()

0      False
1      False
2      False
3      False
4      False
       ...
196    False
197    False
198    False
199    False
200    False
Name: product_category, Length: 201, dtype: bool

In [63]:
ghost_cust_df=pd.merge(customer_df,transaction_df,how="left")[pd.merge(customer_df,transaction_df,how="left")["product_category"].isna()]

In [62]:
pd.merge(customer_df,transaction_df,how="left")["product_category"].isna().sum()

np.int64(1)

In [64]:
ghost_cust_df

,customer_id,store,age,gender,membership_level,signup_date,transaction_id,date,amount,product_category
28,7,E,19,F,Silver,2022-01-07,NaN,NaT,NaN,NaN