In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../datasets/SS_meridian.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [4]:
df.memory_usage()

Index           132
PassengerId    5528
Survived       5528
Pclass         5528
Name           5528
Sex            5528
Age            5528
SibSp          5528
Parch          5528
Ticket         5528
Fare           5528
Cabin          5528
Embarked       5528
dtype: int64

In [5]:
df.memory_usage().sum()

np.int64(66468)

In [6]:
df.memory_usage().sum()/1000

np.float64(66.468)

In [7]:
df.memory_usage(deep=True)

Index            132
PassengerId     5528
Survived        5528
Pclass          5528
Name           46844
Sex            37177
Age             5528
SibSp           5528
Parch           5528
Ticket         38696
Fare            5528
Cabin          25092
Embarked       34550
dtype: int64

In [8]:
df.memory_usage(deep=True).sum()/1000

np.float64(221.187)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  691 non-null    int64
 1   Survived     691 non-null    int64
 2   Pclass       691 non-null    int64
 3   Name         691 non-null    object
 4   Sex          691 non-null    object
 5   Age          634 non-null    float64
 6   SibSp        691 non-null    int64
 7   Parch        691 non-null    int64
 8   Ticket       691 non-null    object
 9   Fare         691 non-null    float64
 10  Cabin        149 non-null    object
 11  Embarked     691 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 64.9+ KB

In [9]:
df.Sex.unique()

array(['female', 'male'], dtype=object)

In [13]:
df.Sex=df.Sex.astype("category")

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  691 non-null    int64
 1   Survived     691 non-null    int64
 2   Pclass       691 non-null    int64
 3   Name         691 non-null    object
 4   Sex          691 non-null    category
 5   Age          634 non-null    float64
 6   SibSp        691 non-null    int64
 7   Parch        691 non-null    int64
 8   Ticket       691 non-null    object
 9   Fare         691 non-null    float64
 10  Cabin        149 non-null    object
 11  Embarked     691 non-null    object
dtypes: category(1), float64(2), int64(5), object(4)
memory usage: 60.3+ KB

In [15]:
df.memory_usage()

Index           132
PassengerId    5528
Survived       5528
Pclass         5528
Name           5528
Sex             815
Age            5528
SibSp          5528
Parch          5528
Ticket         5528
Fare           5528
Cabin          5528
Embarked       5528
dtype: int64

In [16]:
df.memory_usage(deep=True)

Index            132
PassengerId     5528
Survived        5528
Pclass          5528
Name           46844
Sex              907
Age             5528
SibSp           5528
Parch           5528
Ticket         38696
Fare            5528
Cabin          25092
Embarked       34550
dtype: int64

In [17]:
df.memory_usage(deep=True).sum()/1000

np.float64(184.917)

In [18]:
df.Embarked=df.Embarked.astype("category")

In [19]:
df.memory_usage(deep=True)#.sum()/1000

Index            132
PassengerId     5528
Survived        5528
Pclass          5528
Name           46844
Sex              907
Age             5528
SibSp           5528
Parch           5528
Ticket         38696
Fare            5528
Cabin          25092
Embarked         949
dtype: int64

In [20]:
df.memory_usage(deep=True).sum()/1000

np.float64(151.316)

In [21]:
df.Ticket.unique()

array(['SM70415', 'SM69589', 'SM43901', 'SM68491', 'SM16863', 'SM34535',
       'SM66985', 'SM37886', 'SM87459', 'SM58085', 'SM42189', 'SM20561',
       'SM80776', 'SM86865', 'SM12587', 'SM59664', 'SM22648', 'SM99505',
       'SM86271', 'SM28350', 'SM51229', 'SM77889', 'SM66372', 'SM54767',
       'SM39603', 'SM24984', 'SM97135', 'SM53452', 'SM19514', 'SM84572',
       'SM37147', 'SM70314', 'SM24790', 'SM35106', 'SM99694', 'SM89478',
       'SM54433', 'SM65058', 'SM12688', 'SM19744', 'SM71039', 'SM21128',
       'SM28434', 'SM55603', 'SM69616', 'SM40924', 'SM95426', 'SM88134',
       'SM93719', 'SM17120', 'SM83685', 'SM97994', 'SM84498', 'SM85082',
       'SM99285', 'SM29848', 'SM11461', 'SM65965', 'SM43972', 'SM14278',
       'SM45227', 'SM16380', 'SM95848', 'SM34264', 'SM62772', 'SM97026',
       'SM26011', 'SM93681', 'SM76949', 'SM26315', 'SM96252', 'SM65797',
       'SM15529', 'SM77411', 'SM54077', 'SM62187', 'SM17087', 'SM23425',
       'SM39548', 'SM51591', 'SM38298', 'SM16648', 'SM52899', 'SM58629',
       'SM10110', 'SM29871', 'SM85397', 'SM99573', 'SM25509', 'SM17362',
       'SM43361', 'SM27499', 'SM38039', 'SM32768', 'SM51160', 'SM26389',
       'SM83147', 'SM82132', 'SM82642', 'SM68190', 'SM23019', 'SM20998',
       'SM29405', 'SM75161', 'SM90967', 'SM29601', 'SM27878', 'SM45200',
       'SM90364', 'SM44816', 'SM85784', 'SM63143', 'SM49666', 'SM46467',
       'SM83535', 'SM87894', 'SM36326', 'SM18569', 'SM88470', 'SM22387',
       'SM95317', 'SM58623', 'SM90149', 'SM79806', 'SM24539', 'SM19556',
       'SM69770', 'SM89194', 'SM75803', 'SM71835', 'SM41552', 'SM42447',
       'SM63627', 'SM98832', 'SM57964', 'SM33474', 'SM11256', 'SM33021',
       'SM95344', 'SM89635', 'SM50846', 'SM36398', 'SM69270', 'SM81496',
       'SM20580', 'SM92388', 'SM63562', 'SM85525', 'SM54663', 'SM55640',
       'SM33306', 'SM10131', 'SM15798', 'SM32701', 'SM37102', 'SM27598',
       'SM30836', 'SM55224', 'SM83946', 'SM99381', 'SM29566', 'SM79979',
       'SM60785', 'SM59089', 'SM21247', 'SM89670', 'SM58310', 'SM67154',
       'SM27001', 'SM38864', 'SM90918', 'SM28837', 'SM84455', 'SM81197',
       'SM10617', 'SM64493', 'SM24806', 'SM69898', 'SM42706', 'SM41760',
       'SM52026', 'SM38574', 'SM22672', 'SM38632', 'SM22560', 'SM49309',
       'SM53286', 'SM98117', 'SM91940', 'SM64040', 'SM40422', 'SM29978',
       'SM21959', 'SM81582', 'SM65498', 'SM69441', 'SM28659', 'SM32149',
       'SM28293', 'SM52622', 'SM44760', 'SM28030', 'SM13788', 'SM57277',
       'SM14861', 'SM72245', 'SM96356', 'SM70981', 'SM69929', 'SM39400',
       'SM61505', 'SM66155', 'SM29162', 'SM25674', 'SM81620', 'SM36896',
       'SM52840', 'SM55068', 'SM58466', 'SM23133', 'SM85132', 'SM84202',
       'SM80305', 'SM66532', 'SM33496', 'SM71503', 'SM67104', 'SM87376',
       'SM90151', 'SM66980', 'SM99779', 'SM72773', 'SM51999', 'SM27423',
       'SM45187', 'SM50906', 'SM46452', 'SM58258', 'SM64767', 'SM74634',
       'SM80464', 'SM65382', 'SM29558', 'SM18601', 'SM57294', 'SM82512',
       'SM75038', 'SM51116', 'SM31992', 'SM74517', 'SM59518', 'SM92306',
       'SM69468', 'SM98487', 'SM57395', 'SM26728', 'SM75382', 'SM60934',
       'SM54909', 'SM31802', 'SM58717', 'SM20350', 'SM75054', 'SM83420',
       'SM99241', 'SM35415', 'SM87924', 'SM25435', 'SM10464', 'SM74440',
       'SM27527', 'SM22793', 'SM49612', 'SM27536', 'SM18566', 'SM52056',
       'SM16428', 'SM27395', 'SM48800', 'SM89395', 'SM44513', 'SM14722',
       'SM68891', 'SM42353', 'SM87397', 'SM94922', 'SM84529', 'SM29484',
       'SM83681', 'SM55544', 'SM88647', 'SM70909', 'SM55508', 'SM36549',
       'SM52917', 'SM84814', 'SM33086', 'SM72422', 'SM31697', 'SM89073',
       'SM30582', 'SM47353', 'SM60579', 'SM17552', 'SM64127', 'SM77662',
       'SM80284', 'SM99073', 'SM42457', 'SM91080', 'SM25493', 'SM71474',
       'SM62642', 'SM23970', 'SM18581', 'SM48983', 'SM33425', 'SM69840',
       'SM78569', 'SM16014', 'SM69905', 'SM97826', 'SM19071', 'SM61347',
       'SM63008', 'SM60556', 'SM54606', 'SM19742', 'SM16734', 'SM29936',
       'SM82368', 'SM27294', 'SM92279', 'SM62354', 'SM36208', 'SM88494',
       'SM37815', 'SM78534', 'SM80236', 'SM74415', 'SM92090', 'SM81618',
       'SM29826', 'SM13901', 'SM93930', 'SM40841', 'SM84978', 'SM31409',
       'SM44483', 'SM24336', 'SM42771', 'SM86543', 'SM16764', 'SM71894',
       'SM84341', 'SM18200', 'SM48477', 'SM87283', 'SM79489', 'SM29278',
       'SM37082', 'SM84762', 'SM37483', 'SM70910', 'SM48005', 'SM99074',
       'SM67464', 'SM59634', 'SM64675', 'SM85248', 'SM55069', 'SM35652',
       'SM60132', 'SM54284', 'SM11056', 'SM57381', 'SM30715', 'SM23742',
       'SM59827', 'SM66280', 'SM19757', 'SM12170', 'SM70852', 'SM89076',
       'SM71066', 'SM22803', 'SM25336', 'SM71228', 'SM40464', 'SM49478',
       'SM33784', 'SM11110', 'SM76402', 'SM60012', 'SM85574', 'SM22656',
       'SM10753', 'SM74491', 'SM36832', 'SM15572', 'SM51120', 'SM91399',
       'SM43425', 'SM49562', 'SM28569', 'SM42087', 'SM79355', 'SM92111',
       'SM21053', 'SM22098', 'SM11469', 'SM40107', 'SM34696', 'SM75726',
       'SM82358', 'SM96997', 'SM38143', 'SM60422', 'SM38830', 'SM95322',
       'SM45268', 'SM95089', 'SM10455', 'SM12453', 'SM13617', 'SM89388',
       'SM89405', 'SM92441', 'SM18127', 'SM94108', 'SM49251', 'SM80010',
       'SM66072', 'SM22661', 'SM32843', 'SM78012', 'SM87660', 'SM20245',
       'SM21725', 'SM95037', 'SM78197', 'SM86556', 'SM93863', 'SM44690',
       'SM66694', 'SM10887', 'SM62096', 'SM62037', 'SM70903', 'SM11032',
       'SM80328', 'SM75333', 'SM36365', 'SM37180', 'SM18481', 'SM91352',
       'SM47560', 'SM18357', 'SM73614', 'SM42749', 'SM26515', 'SM86076',
       'SM50907', 'SM59781', 'SM49405', 'SM48289', 'SM66906', 'SM94790',
       'SM53634', 'SM17094', 'SM26822', 'SM89254', 'SM20480', 'SM46335',
       'SM46666', 'SM25031', 'SM34931', 'SM49930', 'SM42728', 'SM40497',
       'SM75866', 'SM45910', 'SM81932', 'SM19296', 'SM73176', 'SM60738',
       'SM48558', 'SM42859', 'SM16932', 'SM49008', 'SM23114', 'SM91962',
       'SM98761', 'SM52030', 'SM77215', 'SM17128', 'SM15856', 'SM21728',
       'SM96278', 'SM80381', 'SM89242', 'SM90960', 'SM36305', 'SM39571',
       'SM74930', 'SM53365', 'SM59941', 'SM19506', 'SM63347', 'SM38091',
       'SM27133', 'SM79922', 'SM40870', 'SM59969', 'SM70106', 'SM44227',
       'SM82151', 'SM95191', 'SM60202', 'SM30719', 'SM85527', 'SM31206',
       'SM69772', 'SM31495', 'SM67549', 'SM34727', 'SM26762', 'SM30926',
       'SM68065', 'SM28705', 'SM32900', 'SM85399', 'SM99816', 'SM83537',
       'SM32361', 'SM30325', 'SM27675', 'SM98225', 'SM99463', 'SM95016',
       'SM37887', 'SM84141', 'SM59638', 'SM17455', 'SM84323', 'SM48987',
       'SM18523', 'SM14705', 'SM86544', 'SM62506', 'SM61807', 'SM62564',
       'SM59391', 'SM31229', 'SM95463', 'SM64146', 'SM26880', 'SM77147',
       'SM36812', 'SM11274', 'SM44180', 'SM49363', 'SM43468', 'SM67340',
       'SM73656', 'SM55140', 'SM32570', 'SM20271', 'SM61733', 'SM17346',
       'SM90589', 'SM92941', 'SM20084', 'SM98428', 'SM96246', 'SM84128',
       'SM33777', 'SM85989', 'SM83616', 'SM19545', 'SM87810', 'SM28664',
       'SM76088', 'SM56952', 'SM38476', 'SM15144', 'SM90405', 'SM31135',
       'SM44136', 'SM68059', 'SM65872', 'SM13816', 'SM71707', 'SM54801',
       'SM57044', 'SM70387', 'SM11330', 'SM93705', 'SM16572', 'SM67536',
       'SM77256', 'SM38905', 'SM56064', 'SM19872', 'SM16202', 'SM82536',
       'SM75774', 'SM55843', 'SM89450', 'SM52830', 'SM26821', 'SM55830',
       'SM80592', 'SM37297', 'SM37471', 'SM23238', 'SM53694', 'SM80879',
       'SM63713', 'SM51224', 'SM28163', 'SM36370', 'SM88632', 'SM77740',
       'SM25403', 'SM40305', 'SM32184', 'SM90434', 'SM46418', 'SM11105',
       'SM39912', 'SM94500', 'SM82596', 'SM75767', 'SM18444', 'SM95078',
       'SM12816', 'SM66689', 'SM46408', 'SM58354', 'SM86064', 'SM59192',
       'SM65690', 'SM88172', 'SM21665', 'SM10336', 'SM79514', 'SM99838',
       'SM59253', 'SM51971', 'SM17019', 'SM25842', 'SM10053', 'SM49789',
       'SM30232', 'SM48270', 'SM22245', 'SM98866', 'SM16743', 'SM19452',
       'SM24408', 'SM66873', 'SM54650', 'SM75513', 'SM24544', 'SM16054',
       'SM23926', 'SM37076', 'SM10611', 'SM99037', 'SM63090', 'SM39451',
       'SM37925', 'SM97251', 'SM29735', 'SM89396', 'SM99664', 'SM57265',
       'SM61952', 'SM12960', 'SM49343', 'SM50043', 'SM39824', 'SM85340',
       'SM95119', 'SM87624', 'SM59207', 'SM30204'], dtype=object)

In [23]:
len(df.Ticket.unique())/df.shape[0]

0.9956584659913169

In [24]:
2**63-1

9223372036854775807

In [25]:
-(2**63-1)

-9223372036854775807

In [26]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,691.000000,691.000000,691.000000,634.000000,691.000000,691.000000,691.000000
mean,346.000000,0.573082,2.108538,31.534385,0.751085,0.560058,35.100593
std,199.618803,0.494988,0.850285,14.198957,0.995051,0.802404,40.895254
min,1.000000,0.000000,1.000000,0.500000,0.000000,0.000000,3.500000
25%,173.500000,0.000000,1.000000,21.225000,0.000000,0.000000,7.440000
50%,346.000000,1.000000,2.000000,31.600000,0.000000,0.000000,15.070000
75%,518.500000,1.000000,3.000000,40.775000,1.000000,1.000000,54.585000
max,691.000000,1.000000,3.000000,74.000000,4.000000,3.000000,203.150000

In [30]:
df.Pclass=df.Pclass.astype("int8")

In [32]:
df.memory_usage(deep=True).sum()/1000

np.float64(146.479)

In [39]:
str(df["Age"].dtype)[:2]

'fl'

In [44]:
def optimize_data_memory(df):
    columns = df.columns
    for column in columns:
        if str(df[column].dtype)[:2]=="in":
            max_int=df[column].max()
            min_int = df[column].min()
            if max_int<127 and min_int>-127:
                df[column] = df[column].astype("int8")
        elif str(df[column].dtype)[:2]=="fl":
            pass
        else:
            len_of_unique= len(df[column].unique())/df.shape[0]
            if len_of_unique<0.15:
                df[column] = df[column].astype("category")

    return df

In [41]:
optimize_data_memory(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
686,687,1,1,"Jackson, Lady Florence",female,34.6,0,0,SM85340,100.78,B72,C
687,688,0,2,"Walker, Mr. Robert",male,34.6,2,0,SM95119,25.18,NaN,M
688,689,1,1,"Jackson, Lady Violet",female,45.7,0,0,SM87624,48.47,NaN,L
689,690,1,1,"Harris, Mrs. Gladys",female,43.2,0,0,SM59207,42.19,D20,M
690,691,0,3,"Green, Mrs. Clara",female,33.1,0,0,SM30204,5.21,NaN,M

In [42]:
df_1=optimize_data_memory(df)

In [43]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  691 non-null    int64
 1   Survived     691 non-null    int8
 2   Pclass       691 non-null    int8
 3   Name         691 non-null    object
 4   Sex          691 non-null    category
 5   Age          634 non-null    float64
 6   SibSp        691 non-null    int8
 7   Parch        691 non-null    int8
 8   Ticket       691 non-null    object
 9   Fare         691 non-null    float64
 10  Cabin        149 non-null    object
 11  Embarked     691 non-null    category
dtypes: category(2), float64(2), int64(1), int8(4), object(3)
memory usage: 36.8+ KB