In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../datasets/SS_meridian.csv")

In [3]:
p_class_grouping=df.groupby("Pclass")

In [4]:
p_class_grouping["Fare"].mean()

Pclass
1    85.836389
2    18.748533
3     7.780481
Name: Fare, dtype: float64

In [5]:
p_class_grouping["Fare"].sum()

Pclass
1    18540.66
2     3449.73
3     2264.12
Name: Fare, dtype: float64

In [6]:
p_class_grouping["Fare"].count()

Pclass
1    216
2    184
3    291
Name: Fare, dtype: int64

In [7]:
p_class_grouping["Fare"].agg(["sum","mean","count"])

             sum       mean  count
Pclass
1       18540.66  85.836389    216
2        3449.73  18.748533    184
3        2264.12   7.780481    291

In [8]:
p_class_grouping.agg(
    total_fare=("Fare","mean"),
    mean_fare=("Fare","sum"),
    no_of_individuals=("Fare","count")
)

        total_fare  mean_fare  no_of_individuals
Pclass
1        85.836389   18540.66                216
2        18.748533    3449.73                184
3         7.780481    2264.12                291

In [9]:
p_class_grouping.agg(
    avg_fare=("Fare","mean"),
    no_of_tickets=("Ticket","count"),
    avg_age=("Age","mean")
)

         avg_fare  no_of_tickets    avg_age
Pclass
1       85.836389            216  40.958706
2       18.748533            184  28.689157
3        7.780481            291  26.208614

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [13]:
df.groupby(["Pclass","Sex"])["Ticket"].count()

Pclass  Sex
1       female    110
        male      106
2       female     89
        male       95
3       female     78
        male      213
Name: Ticket, dtype: int64

In [16]:
df.groupby(["Pclass","Sex"])["Ticket"].count().unstack()

Sex     female  male
Pclass
1          110   106
2           89    95
3           78   213

In [14]:
df.groupby(["Sex","Pclass"])["Ticket"].count()

Sex     Pclass
female  1         110
        2          89
        3          78
male    1         106
        2          95
        3         213
Name: Ticket, dtype: int64

In [15]:
df.groupby(["Sex","Pclass"])["Ticket"].count().unstack()

Pclass    1   2    3
Sex
female  110  89   78
male    106  95  213

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [20]:
df.groupby(["Pclass"])["Ticket"].transform("count")

0      291
1      291
2      184
3      184
4      216
      ...
686    216
687    184
688    216
689    216
690    291
Name: Ticket, Length: 691, dtype: int64

In [26]:
df.groupby(["Pclass"])["Ticket"].agg("count")

Pclass
1    216
2    184
3    291
Name: Ticket, dtype: int64

In [24]:
df["no_of_tickets_by_class"]=df.groupby(["Pclass"])["Ticket"].transform("count")

In [22]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,no_of_tickets_by_class
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M,291
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L,291
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C,184
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L,184
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C,216