In [1]:
import pandas as pd

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [2]:
df=pd.read_csv("../datasets/SS_meridian.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Clark, Miss Mabel",female,22.9,2,1,SM70415,3.50,NaN,M
1,2,1,3,"Lewis, Miss Margaret",female,59.8,1,0,SM69589,4.35,NaN,L
2,3,1,2,"Garcia, Mrs. Anna",female,NaN,1,0,SM43901,14.88,NaN,C
3,4,0,2,"Parker, Mrs. Violet",female,27.7,0,1,SM68491,26.51,NaN,L
4,5,1,1,"Adams, Miss Rose",female,52.1,1,1,SM16863,65.47,NaN,C

In [4]:
df.groupby("Pclass")

In [5]:
df.groupby("Pclass")["Ticket"]

In [6]:
df.groupby("Pclass")["Ticket"].count()

Pclass
1    216
2    184
3    291
Name: Ticket, dtype: int64

In [7]:
df.Pclass.value_counts()

Pclass
3    291
1    216
2    184
Name: count, dtype: int64

In [8]:
p_class_grouping=df.groupby("Pclass")

In [9]:
p_class_grouping["Ticket"].count()

Pclass
1    216
2    184
3    291
Name: Ticket, dtype: int64

In [10]:
p_class_grouping["Fare"].sum()

Pclass
1    18540.66
2     3449.73
3     2264.12
Name: Fare, dtype: float64

In [11]:
p_class_grouping["Fare"].mean()

Pclass
1    85.836389
2    18.748533
3     7.780481
Name: Fare, dtype: float64